openapi: 3.0.3
info:
    title: Vendors API
    description: Vendors API
    version: 1.0.0

paths:
    /api/products:
        post:
            tags:
                - ListProducts
            summary: Products List
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ProductItem'
                401:
                    description: Unauthorized
                500:
                    description: Internal server error
    /api/product{product_id}:
        get:
            tags:
                - Product
            summary: Product
            parameters:
                - in: path
                  name: product_id
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProductItem'
                401:
                    description: Unauthorized
                500:
                    description: Internal server error

components:
    schemas:
        ProductItem:
            type: object
            required:
                - id
                - name
            properties:
                id:
                    type: integer
                name:
                    example: 'Хинкали'
                    type: string
                category_id:
                    type: integer
                description:
                    example: 'Описание продукта'
                    type: string
                price:
                    example: 100
                    type: integer
                image:
                    example: 'https://example.com/image.jpg'
                    type: string
                weight:
                    example: 100
                    type: integer
                status:
                    example: 'new'
                    type: string
                    enum:
                        - new
                        - popular
                        - sale
                    description: 'Статус продукта'
                kcal:
                    example: 100
                    type: integer
                    description: 'Калорийность продукта'
